# Self Driving Wiki — native macOS SwiftUI wiki with a filesystem projection
#
# Quick start:
#   make           # debug-builds via SwiftPM into ./build/Self Driving Wiki.app
#   make run       # build + launch
#   make check     # compile only, no bundling/signing (agent / CI gate)
#   make install   # copy to /Applications/ and register with LaunchServices
#   make help      # full target list
#
# Build is driven by `swift build` + ./build.sh — NO Xcode IDE, NO
# xcodebuild, NO XcodeGen. Xcode is only a toolchain provider (swift /
# codesign / notarytool / stapler). The release/notarization pipeline is
# wired but unused until v0 ships; `make dist` produces a signed-and-stapled
# release zip.

CONFIG       := debug
APP_NAME      := Self Driving Wiki
APP          := build/$(APP_NAME).app
INSTALLED_APP := /Applications/$(APP_NAME).app
LEGACY_APP    := /Applications/WikiFS.app
EXT_NAME      := WikiFSFileProvider

# Per-developer signing config (gitignored shell file; see
# signing/local.config.example). build.sh sources it directly; here we extract
# individual values, falling back to the upstream author's defaults when absent.
#   $(call cfg,VARNAME) → value from signing/local.config, or empty.
LOCAL_CONFIG := signing/local.config
cfg = $(shell . $(LOCAL_CONFIG) >/dev/null 2>&1 && printf '%s' "$$$(1)")

EXT_BUNDLE_ID := $(or $(call cfg,EXT_BUNDLE_ID),org.sockpuppet.WikiFS.FileProvider)
APP_GROUP      := $(or $(call cfg,APP_GROUP),group.org.sockpuppet.wiki)
# Shared keychain access group (app + wikid daemon). Derived per-developer from
# TEAM_ID + APP_GROUP (the App Group minus its "group." prefix, team-prefixed —
# Apple requires the Team ID prefix on keychain-access-groups). Override with
# KEYCHAIN_ACCESS_GROUP in signing/local.config. build.sh and tools/keychaingen
# use the SAME formula, so app, daemon, and code agree. Deferred assignment (=)
# so $(TEAM_ID) (defined further below) is expanded at use time, not now.
# See plans/keychain-sharing.md.
KEYCHAIN_ACCESS_GROUP = $(or $(call cfg,KEYCHAIN_ACCESS_GROUP),$(TEAM_ID).$(patsubst group.%,%,$(APP_GROUP)))
LSREGISTER   := /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister
PLUGINKIT    := pluginkit
MIN_MACOS    := 14
MIN_SWIFT    := 6.0

# Fast test tier — skips the slow SQLite integration suites (tagged
# .integration) for quick PR feedback. This is the same skip list the CI
# `swift` job uses (issue #292); the `swift-integration` job runs the full
# suite with no skip. Shared by `test-fast` (debug) and `test-fast-release`.
FAST_TEST_SKIP := 'EnumeratorDeletionTests|SQLiteWikiStoreTests|StoreEmissionTests|FreshSchemaParityTests|SQLiteStatementLifecycleIntegrationTests|BlobVacuumTests|AgentCASTests|GenerationGateLaneTests|WorkspaceStagingTests|WorkspaceMergeCompletenessTests|IngestIsolationTests|ChatSummaryTests|ProjectionTreeTests|ACPRegistryTests/loadAgentsReturnsNonEmpty'

# Generated by build.sh from the resolved identifiers (not a committed file).
ENTITLEMENTS  := build/WikiFS.entitlements

# Agent-prompt resources (prompts/*.md → Sources/WikiFSCore/Resources/Prompts/).
# The .md files are the canonical source in prompts/; `make prompts` syncs them
# into the WikiFSCore target's Resources directory so SwiftPM bundles them via
# .copy(["Resources/Prompts"]). They are loaded at runtime via Bundle.module
# (see PromptLoader.swift). The copies ARE committed — they are build inputs.
PROMPT_SOURCES    := $(wildcard prompts/*.md)
PROMPT_RESOURCES   := $(PROMPT_SOURCES:prompts/%.md=Sources/WikiFSCore/Resources/Prompts/%.md)

# Version codegen (git state → a GENERATED, gitignored Swift file with
# appVersion, gitSHA, gitCommitCount, buildVersion). Same pattern as promptgen
# above: the file is NOT committed (git is already the source of truth, so a
# committed snapshot would drift on every commit); `make version` regenerates it
# from the current git state and is a prereq of build/check/test/release. The
# generator only writes when content actually changes, so the .PHONY prereq
# doesn't force recompilation on every invocation.
VERSIONGEN_SCRIPT  := tools/versiongen/main.swift
GENERATED_VERSION  := Sources/WikiFSCore/GeneratedVersion.swift
# Shared keychain access group codegen (app + wikid daemon). Same contract as
# version codegen above: gitignored, regenerated from signing/local.config, a
# prerequisite of build/check/test. See tools/keychaingen/main.swift.
KEYCHAINGEN_SCRIPT := tools/keychaingen/main.swift
GENERATED_KEYCHAIN := Sources/WikiFSCore/GeneratedKeychain.swift

# ---------------------------------------------------------------------------
# Release variables
# ---------------------------------------------------------------------------
# Version is resolved in this order:
#   1. VERSION=... on the command line (one-off testing, no tag needed).
#   2. An exact `vX.Y.Z` git tag at HEAD (the canonical `make dist` path).
#   3. The VERSION file at the repo root (so contributors can preview the
#      pipeline without tagging first; `make dist` still requires the tag).
GIT_TAG_VERSION := $(shell git describe --tags --exact-match --match 'v[0-9]*' 2>/dev/null | sed 's/^v//')
FILE_VERSION    := $(shell test -f VERSION && sed -n '1p' VERSION | tr -d '[:space:]')
VERSION         ?= $(or $(GIT_TAG_VERSION),$(FILE_VERSION))

DIST_DIR      := dist
NOTARY_ZIP    := $(DIST_DIR)/$(APP_NAME)-$(VERSION)-notary.zip
RELEASE_ZIP   := $(DIST_DIR)/$(APP_NAME)-$(VERSION)-macos.zip

# Dev signing identity (used by ./build.sh for `make build`/`make run`). Falls
# back to ad-hoc ("-") if the named identity is missing — fine for `make run`
# on your own machine.
DEV_IDENTITY  ?= $(or $(call cfg,DEV_IDENTITY),Apple Development: Thomas Ptacek (7F2QE7P59D))

# Distribution signing identity (Developer ID Application). Used by `make
# release` / `make dist` / `make notarize` (#746): build.sh signs every nested
# component (app, appex, helpers) with this inside-out, then `make sign` re-signs
# the outer app with CERT_NAME + hardened runtime + timestamp. Falls back to
# ad-hoc ("-") in build.sh if unset/missing — but `make sign` will then fail
# loudly (CERT_NAME empty or not in keychain), so a notarized release cannot
# silently ship with the wrong cert. Leave empty until you've issued a Developer
# ID Application cert (see signing/local.config.example + plans/fix-signing-cert.md).
DIST_IDENTITY ?= $(or $(call cfg,DIST_IDENTITY),)

# Distribution signing. Developer ID + hardened runtime + notarization.
# CERT_NAME (used by `make sign`) resolves from DIST_IDENTITY; a hand-set
# CERT_NAME in local.config still wins (backwards compat).
TEAM_ID       ?= $(or $(call cfg,TEAM_ID),KK7E9G89GW)
CERT_NAME     ?= $(or $(call cfg,CERT_NAME),$(DIST_IDENTITY),Developer ID Application: Thomas Ptacek ($(TEAM_ID)))

# Notarization credentials profile name. Populate once with
# `make notary-setup` (interactive; never puts the password on the cmdline).
NOTARY_PROFILE ?= wikifs-notary

PROVISION_PROFILE ?=
NOTES_FILE       ?=

.PHONY: all deps build check check-release test test-fast test-fast-release release run reload clean install uninstall register help prune-provider-registrations \
        check-version notary-setup sign zip-notary notarize staple zip-release \
        checksum verify-release dist github-release print-version icon prompts \
        version keychain mutate mutate-scope

all: build

help:
	@echo "Build:"
	@echo "  make / build      Build $(CONFIG) into ./$(APP)  (default)"
	@echo "                    (also builds ./build/wikictl + embeds it in the app bundle)"
	@echo "  check             Compile only (swift build) — no bundle/sign; CI/agent gate"
	@echo "  check-release     Compile only in release mode (swift build -c release)"
	@echo "  test              Run the SwiftPM test suite"
	@echo "  test-fast         Fast test tier (debug) — skips slow SQLite integration suites"
	@echo "  test-fast-release Fast test tier in release mode (faster runtime, slower compile)"
	@echo "  mutate            Run swift-mutation-testing (full — see .swift-mutation-testing.yml)"
	@echo "  mutate-scope      Scoped mutation run: make mutate-scope SOURCES_PATH=Sources/Foo"
	@echo "  prompts           Regenerate Sources/WikiFSCore/GeneratedPrompts.swift from prompts/*.md"
	@echo "                    (gitignored — regenerated by build/check/test)"
	@echo "  version           Regenerate Sources/WikiFSCore/GeneratedVersion.swift from git state"
	@echo "                    (gitignored — regenerated by build/check/test)"
	@echo "  keychain          Regenerate Sources/WikiFSCore/GeneratedKeychain.swift from signing/local.config"
	@echo "                    (gitignored — app + wikid daemon shared keychain access group)"
	@echo "  release           Build release into ./$(APP)"
	@echo "  run               Install to /Applications and launch $(APP_NAME)"
	@echo "  reload            Like run, but forces the File Provider domain to reset —"
	@echo "                    use after changing FileProvider rendering (Projection.swift,"
	@echo "                    PageMarkdownFormat, RelativeLinkRewriter, …); the daemon"
	@echo "                    caches materialized files by data version, so a rendering-only"
	@echo "                    change is otherwise invisible until content is next edited"
	@echo "  clean             Remove ./build/ ./.build/ ./dist/"
	@echo "  deps              Verify build prerequisites (auto-run before build)"
	@echo ""
	@echo "Local install:"
	@echo "  install           Copy $(APP_NAME).app to /Applications/ and register app + File Provider"
	@echo "  uninstall         Remove /Applications/$(APP_NAME).app"
	@echo "  register          Same as install; File Provider must run from /Applications"
	@echo ""
	@echo "Release pipeline (require an exact 'vX.Y.Z' git tag):"
	@echo "  notary-setup      One-time: store notary creds in keychain ($(NOTARY_PROFILE))"
	@echo "  dist              Build → sign → notarize → staple → zip → checksum"
	@echo "  github-release    Upload \$$(RELEASE_ZIP) + .sha256 to a GitHub release"
	@echo "  sign              codesign Developer ID + hardened runtime + timestamp"
	@echo "  notarize          Submit to Apple (keychain profile $(NOTARY_PROFILE))"
	@echo "  staple            xcrun stapler staple"
	@echo "  verify-release    spctl + codesign sanity-check the bundle"
	@echo "  print-version     Print resolved release VERSION"
	@echo ""
	@echo "  help              Show this message"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

deps:
	@echo "→ Checking build prerequisites..."
	@OS_VERSION=$$(sw_vers -productVersion 2>/dev/null); \
	if [ -z "$$OS_VERSION" ]; then \
	  echo "  ✗ Could not detect macOS version. $(APP_NAME) only builds on macOS."; exit 1; \
	fi; \
	OS_MAJOR=$$(echo $$OS_VERSION | cut -d. -f1); \
	if [ $$OS_MAJOR -lt $(MIN_MACOS) ]; then \
	  echo "  ✗ macOS $$OS_VERSION — $(APP_NAME) requires macOS $(MIN_MACOS).0 or newer."; exit 1; \
	fi; \
	echo "  ✓ macOS $$OS_VERSION"
	@command -v swift >/dev/null 2>&1 || { \
	  echo "  ✗ swift not on PATH. Install Xcode (App Store) or the Swift toolchain"; \
	  echo "    from https://swift.org/install/macos/, then re-run."; exit 1; }
	@SW_LINE=$$(swift --version 2>&1 | head -1); \
	echo "  ✓ $$SW_LINE"
	@[ -f Package.swift ] || { echo "  ✗ Package.swift not found. Run make from the repo root."; exit 1; }
	@echo "  ✓ Package.swift present"
	@[ -x ./build.sh ] || { echo "  ✗ ./build.sh missing or not executable."; exit 1; }
	@echo "  ✓ build.sh present"
	@echo "→ Prerequisites OK."

# bun is required for the full .app build (bundled into Contents/Helpers for
# ACP providers), but NOT for `check`/`test` which only call `swift build`/
# `swift test`. Gate it here as a prereq of build/release only. See #762.
# Resolution: BUN_INSTALL/bin/bun → ~/.bun/bin/bun → `command -v bun` (PATH).
bun-check:
	@BUN_SRC="${BUN_INSTALL:-$$HOME/.bun}/bin/bun"; \
	if [ ! -x "$$BUN_SRC" ]; then BUN_SRC=$$(command -v bun 2>/dev/null || true); fi; \
	if [ -z "$$BUN_SRC" ] || [ ! -x "$$BUN_SRC" ]; then \
	  echo "✗ FATAL: bun not found" >&2; \
	  echo "    Install it:  curl -fsSL https://bun.sh/install | bash" >&2; \
	  echo "    Or set BUN_INSTALL to point at your bun binary's directory." >&2; \
	  exit 1; \
	fi
	@echo "  ✓ bun found"

# ---------------------------------------------------------------------------
# Build (delegates to ./build.sh: swift build + bundle + codesign)
# ---------------------------------------------------------------------------

ICON_SCRIPT := scripts/make-icon.swift
APP_ICON    := build/AppIcon.icns

# App icon: regenerated when the script changes. The script renders a white
# `books.vertical.fill` SF Symbol on a blue→indigo squircle at every macOS
# icon size; iconutil packages them. Output: build/AppIcon.icns, copied into
# the .app bundle by build.sh.
$(APP_ICON): $(ICON_SCRIPT)
	@mkdir -p build
	@swift $(ICON_SCRIPT)
	@iconutil -c icns build/AppIcon.iconset -o $(APP_ICON)
	@echo "✓ $(APP_ICON)"

icon: $(APP_ICON)

build: deps bun-check $(APP_ICON) prompts version keychain
	SIGN_IDENTITY="$(DEV_IDENTITY)" PROVISION_PROFILE="$(PROVISION_PROFILE)" ./build.sh $(CONFIG)

# Release signs with DIST_IDENTITY (Developer ID Application) so every nested
# component (app, appex, helpers) carries the distribution cert inside-out
# (#746). `make sign` then re-signs the outer app with the same identity +
# hardened runtime + timestamp for notarization. The old code passed
# DEV_IDENTITY here, which signed release builds with the Apple Development
# cert → notarytool rejected it and Gatekeeper rejected it on other machines.
release: deps bun-check $(APP_ICON) prompts version keychain
	SIGN_IDENTITY="$(DIST_IDENTITY)" PROVISION_PROFILE="$(PROVISION_PROFILE)" ./build.sh release

# Compile-only gate — no .app, no signing. CI / agent verification.
check: deps prompts version keychain
	swift build -c $(CONFIG)
	@echo "✓ compiles ($(CONFIG))"

# Compile-only gate in RELEASE mode — no .app, no signing. Faster runtime
# than `check` at the cost of slower compile; use for performance testing or
# when you want the code path optimized. (issue #520)
check-release: deps prompts version keychain
	swift build -c release
	@echo "✓ compiles (release)"

# Run the test suite.
test: deps prompts version keychain
	swift test
	@echo "✓ tests pass"

# Fast test tier (debug) — skips the slow SQLite integration suites for quick
# PR feedback. Run `make test` for the full suite. (issue #520)
test-fast: deps prompts version keychain
	swift test --skip $(FAST_TEST_SKIP)
	@echo "✓ fast tests pass (debug)"

# Fast test tier in RELEASE mode — faster runtime, slower compile. Same skip
# list as `test-fast`; for performance-testing the suite itself. (issue #520)
test-fast-release: deps prompts version keychain
	swift test -c release --skip $(FAST_TEST_SKIP)
	@echo "✓ fast tests pass (release)"

# ---------------------------------------------------------------------------
# Mutation testing (swift-mutation-testing — schematized mutator runs)
# ---------------------------------------------------------------------------
#
# swift-mutation-testing v1.3.0+ builds the project once, then re-runs the
# test suite for every mutant via a runtime switch (no per-mutant recompile).
# Config lives in .swift-mutation-testing.yml at the repo root. Install:
#
#   brew tap ericodx/homebrew-tools
#   brew install ericodx/homebrew-tools/swift-mutation-testing
#
# `mutate`         — full run (all sources, all configured mutators).
# `mutate-scope`   — scoped to a single source directory via SOURCES_PATH:
#
#   make mutate-scope SOURCES_PATH=Sources/WikiFSTypes
#
# Reports are written to mutation-report.json (+ .html / sonar-*.json if
# uncommented in the config); the result cache lives in
# .swift-mutation-testing-cache/. Both are gitignored.

mutate: deps prompts version keychain
	swift-mutation-testing
	@echo "✓ mutation testing complete — see mutation-report.json"

mutate-scope: deps prompts version keychain
	@if [ -z "$(SOURCES_PATH)" ]; then \
	  echo "✗ SOURCES_PATH is required. Example:"; \
	  echo "    make mutate-scope SOURCES_PATH=Sources/WikiFSTypes"; \
	  exit 1; \
	fi
	swift-mutation-testing --sources-path "$(SOURCES_PATH)"
	@echo "✓ mutation testing complete for $(SOURCES_PATH) — see mutation-report.json"

# ---------------------------------------------------------------------------
# Agent prompts (prompts/*.md → Sources/WikiFSCore/GeneratedPrompts.swift)
# ---------------------------------------------------------------------------

# The .md files in prompts/ are the canonical source; `make prompts` syncs
# them into Sources/WikiFSCore/Resources/Prompts/ where SwiftPM picks them up
# via the .copy(["Resources/Prompts"]) declaration in Package.swift. They are
# loaded at runtime via Bundle.module (see PromptLoader.swift). The resource
# copies ARE committed (they are build inputs), unlike the former
# code-generated GeneratedPrompts.swift.
.PHONY: prompts
prompts:
	@rm -f Sources/WikiFSCore/GeneratedPrompts.swift
	@mkdir -p Sources/WikiFSCore/Resources/Prompts
	@for f in prompts/*.md; do \
		dest="Sources/WikiFSCore/Resources/Prompts/$$(basename $$f)"; \
		if ! diff -q "$$f" "$$dest" >/dev/null 2>&1; then \
			cp "$$f" "$$dest"; \
			echo "prompts: synced $$f"; \
		fi; \
	done

# Version codegen — regenerate the gitignored GeneratedVersion.swift from the
# current git state (tag/VERSION file → appVersion; SHA + commit count →
# buildVersion). Always runs; the generator skips writing if content is
# unchanged, so this doesn't force recompilation on every make invocation. No
# drift gate — the file isn't committed; git is the source of truth.
version:
	@swift $(VERSIONGEN_SCRIPT)

# Keychain access-group codegen — regenerate the gitignored
# GeneratedKeychain.swift from signing/local.config (TEAM_ID + APP_GROUP). Same
# build-time/derived-artifact contract as `version`: the generator only writes
# when content changes, so the .PHONY prerequisite doesn't force a recompile
# every invocation. Empty when local.config is absent (fresh clones / CI / tests
# → "no group" → legacy file keychain). See plans/keychain-sharing.md.
keychain:
	@swift $(KEYCHAINGEN_SCRIPT)

print-version:
	@echo "VERSION=$(VERSION)"
	@echo "  git tag at HEAD: $(if $(GIT_TAG_VERSION),$(GIT_TAG_VERSION),(none))"
	@echo "  VERSION file:    $(if $(FILE_VERSION),$(FILE_VERSION),(missing))"
	@echo "  git SHA:         $$(git rev-parse --short HEAD 2>/dev/null || echo '(unknown)')"
	@echo "  commit count:    $$(git rev-list --count HEAD 2>/dev/null || echo '?')"
	@echo "  build version:   $$(git rev-list --count HEAD 2>/dev/null || echo '0')-$$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

# ---------------------------------------------------------------------------
# Run / install / register
# ---------------------------------------------------------------------------

run: install
	open "$(INSTALLED_APP)"

# `reload` — like `run`, but forces every registered File Provider domain to be
# removed and re-added before it mounts again.
#
# Why this exists: fileproviderd caches each materialized file's bytes keyed
# by the DATA version the extension reports (page.version / chat.updatedAt /
# the whole-DB changeToken — see Projection.swift's `pageFileNode` etc.), NOT
# by the extension's own build/code version. So a rebuild that changes how a
# file is RENDERED (e.g. #216's [[wikilink]] → relative-Markdown-link rewrite)
# is invisible to already-materialized files on disk: the daemon sees the same
# reported version it already cached and never calls back into the extension
# for fresh bytes. A plain `make install`/`run` — even a from-scratch rebuild —
# does not fix this; the stale copies live in fileproviderd's cache, not the
# app bundle. There is no `fileproviderctl` evict/reimport subcommand on this
# OS to force it from the shell, and a raw `rm` on a mounted file round-trips
# through the (read-only) extension's `deleteItem` and is rejected.
#
# The one CLI-drivable fix is the app's own `WIKIFS_REENUMERATE=1` hatch
# (FileProviderFacade.swift `registerDomain`): read once at launch, it calls
# `NSFileProviderManager.remove(domain)` for each wiki before re-adding it —
# tearing down and rebuilding the whole projection, which forces a full
# re-fetch. `open --env` (macOS 14+) sets that var for the freshly-launched
# process; a plain `open` does not propagate shell environment into the
# relaunch, so this can't just be `WIKIFS_REENUMERATE=1 open ...`. Both the
# app and extension processes are killed first so `-n` (new instance) doesn't
# leave a stale, non-reset instance running alongside the fresh one.
#
# This is a one-shot manual hatch for local dev; it is deliberately NOT the
# default `run`/`install` behavior because a full domain reset re-downloads
# everything and would slow down routine iteration unrelated to rendering
# changes. The permanent, no-flag-needed fix for a SHIPPED rendering-contract
# change is bumping `FileProviderFacade.currentSchemaVersion`, which resets
# every user's domain automatically on next launch (see its doc comment) —
# use `reload` here to verify, then decide separately whether the change
# warrants that bump.
reload: install
	@pkill -f "$(INSTALLED_APP)/Contents/MacOS/$(APP_NAME)" 2>/dev/null && echo "✓ killed running $(APP_NAME)" || true
	@pkill -f "$(EXT_NAME).appex" 2>/dev/null && echo "✓ killed stale $(EXT_NAME) process" || true
	@sleep 1
	open --env WIKIFS_REENUMERATE=1 -n "$(INSTALLED_APP)"
	@echo "✓ relaunched $(APP_NAME) with WIKIFS_REENUMERATE=1 — File Provider domain(s) will reset on this launch"

install: build prune-provider-registrations
	@if [ ! -d "$(APP)" ]; then echo "✗ $(APP) missing — build failed?"; exit 1; fi
	@pkill -f "$(EXT_NAME).appex" 2>/dev/null && echo "✓ killed stale $(EXT_NAME) process" || true
	@pkill -f "$(INSTALLED_APP)/Contents/MacOS/$(APP_NAME)" 2>/dev/null && echo "✓ killed running $(APP_NAME)" || true
	rm -rf "$(INSTALLED_APP)"
	cp -R "$(APP)" /Applications/
	@echo "✓ copied to $(INSTALLED_APP)"
	$(LSREGISTER) -f "$(INSTALLED_APP)"
	$(PLUGINKIT) -a "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex"
	$(PLUGINKIT) -e use -i "$(EXT_BUNDLE_ID)" -p com.apple.fileprovider-nonui >/dev/null 2>&1 || true
	@for attempt in 1 2 3; do \
	  if $(PLUGINKIT) -m -p com.apple.fileprovider-nonui -i "$(EXT_BUNDLE_ID)" -A -D -vvv 2>/dev/null \
	    | grep -Fq "Path = $(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex"; then \
	    exit 0; \
	  fi; \
	  sleep 1; \
	done; \
	echo "✗ $(EXT_BUNDLE_ID) did not register at $(INSTALLED_APP)" >&2; \
	$(PLUGINKIT) -m -p com.apple.fileprovider-nonui -i "$(EXT_BUNDLE_ID)" -A -D -vvv 2>&1 || true; \
	exit 1
	@echo "✓ registered $(INSTALLED_APP) and $(EXT_BUNDLE_ID)"

prune-provider-registrations:
	@for appex in \
	  "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "$(APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "$(LEGACY_APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "build/WikiFS.app/Contents/PlugIns/$(EXT_NAME).appex" \
	  "/private/tmp/Wtest.app/Contents/PlugIns/$(EXT_NAME).appex"; do \
	  if [ -d "$$appex" ]; then $(PLUGINKIT) -r "$$appex" >/dev/null 2>&1 || true; fi; \
	done
	@for app in "$(APP)" "$(LEGACY_APP)" "build/WikiFS.app" "/private/tmp/Wtest.app"; do \
	  if [ -d "$$app" ]; then $(LSREGISTER) -u "$$app" >/dev/null 2>&1 || true; fi; \
	done

uninstall:
	@if [ -d "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" ]; then \
	  $(PLUGINKIT) -r "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" >/dev/null 2>&1 || true; \
	fi
	@if [ -d "$(INSTALLED_APP)" ]; then \
	  rm -rf "$(INSTALLED_APP)" 2>/dev/null || sudo rm -rf "$(INSTALLED_APP)"; \
	  echo "✓ removed $(INSTALLED_APP)"; \
	else \
	  echo "  (no $(INSTALLED_APP) to remove)"; \
	fi

register: install

# ---------------------------------------------------------------------------
# wikid daemon — launchd install/uninstall (plans/multi-wiki-daemon.md Phase 1B)
# ---------------------------------------------------------------------------

# wikid daemon — managed by launchctl (the app bootstraps it on launch via
# DaemonLaunchAgentManager). The daemon is unsandboxed: NO entitlements (AMFI
# kills a bare Mach-O that has entitlements but no embedded provisioning
# profile). It reads the app group container directly via filesystem perms.
#
# `make install-daemon` is for dev-mode: signs the .build binary (ad-hoc or
# dev cert), copies it to the container dir, installs a manual launchd plist
# pointing at the container binary + sets WIKI_CONTAINER_DIR. Production:
# the app generates the plist at runtime and bootstraps via launchctl.
WIKID_BIN := $(shell swift build --show-bin-path)/wikid
WIKID_PLIST := signing/com.selfdrivingwiki.wikid.plist
WIKID_PLIST_DST := $(HOME)/Library/LaunchAgents/com.selfdrivingwiki.wikid.plist
WIKID_SIGN_IDENTITY := $(shell grep '^DEV_IDENTITY=' signing/local.config 2>/dev/null | sed 's/DEV_IDENTITY=//; s/^"//; s/"$$//' || echo "-")
WIKID_CONTAINER_DIR := $(HOME)/Library/Group Containers/$(shell grep '^APP_GROUP=' signing/local.config 2>/dev/null | sed 's/APP_GROUP=//; s/^"//; s/"$$//' || echo "group.org.sockpuppet.wiki")
WIKID_UID := $(shell id -u)

.PHONY: install-daemon uninstall-daemon daemon-status

install-daemon: ## Dev-only: install wikid via a manual launchd plist (for .build binaries). Production: app bootstraps via launchctl.
install-daemon:
	@echo "→ Building wikid…"
	@swift build --target wikid
	@echo "→ Copying wikid binary to container dir…"
	@mkdir -p "$(WIKID_CONTAINER_DIR)"
	@cp "$(WIKID_BIN)" "$(WIKID_CONTAINER_DIR)/wikid"
	@echo "→ Codesigning wikid + wikictl (identity: $(WIKID_SIGN_IDENTITY))…"
	@codesign --force --timestamp=none --identifier com.selfdrivingwiki.wikid \
		--sign "$(WIKID_SIGN_IDENTITY)" "$(WIKID_CONTAINER_DIR)/wikid" 2>/dev/null \
		|| codesign --force --timestamp=none --sign - "$(WIKID_CONTAINER_DIR)/wikid"
	@codesign --force --timestamp=none --identifier com.selfdrivingwiki.wikictl \
		--entitlements signing/wikictl.entitlements \
		--sign "$(WIKID_SIGN_IDENTITY)" "$(dir $(WIKID_BIN))wikictl" 2>/dev/null \
		|| codesign --force --timestamp=none --sign - "$(dir $(WIKID_BIN))wikictl"
	@echo "→ Installing launchd plist (dev mode — may prompt for TCC once)…"
	@mkdir -p $(dir $(WIKID_PLIST_DST))
	@cp $(WIKID_PLIST) $(WIKID_PLIST_DST)
	@# Replace the shell-wrapped ProgramArguments with the direct binary path.
	@plutil -remove ProgramArguments -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST) 2>/dev/null || true
	@plutil -insert ProgramArguments -array -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST) 2>/dev/null || true
	@plutil -insert ProgramArguments.0 -string "$(WIKID_CONTAINER_DIR)/wikid" -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST)
	@plutil -insert EnvironmentVariables.WIKI_CONTAINER_DIR -string "$(WIKID_CONTAINER_DIR)" -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST) 2>/dev/null \
		|| { plutil -insert EnvironmentVariables -xml '<dict/>' -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST); \
		     plutil -insert EnvironmentVariables.WIKI_CONTAINER_DIR -string "$(WIKID_CONTAINER_DIR)" -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST); }
	@launchctl bootout gui/$(WIKID_UID)/com.selfdrivingwiki.wikid 2>/dev/null || true
	@launchctl bootstrap gui/$(WIKID_UID) $(WIKID_PLIST_DST)
	@echo "✓ wikid installed (dev mode). Production: app bootstraps via launchctl."
	@echo "  Binary:     $(WIKID_CONTAINER_DIR)/wikid"
	@echo "  Container:  $(WIKID_CONTAINER_DIR)"
	@echo "  Plist:      $(WIKID_PLIST_DST)"
	@echo "  Status:     make daemon-status"

uninstall-daemon: ## Remove the wikid launchd agent
uninstall-daemon:
	@launchctl bootout gui/$(WIKID_UID)/com.selfdrivingwiki.wikid 2>/dev/null || true
	@launchctl unload $(WIKID_PLIST_DST) 2>/dev/null || true
	@rm -f $(WIKID_PLIST_DST)
	@echo "✓ wikid uninstalled."

daemon-status: ## Show the wikid launchd agent status
daemon-status:
	@launchctl list | grep wikid || echo "wikid is not loaded."

approve-daemon: ## Open System Settings → Full Disk Access (add "Self Driving Wiki" to suppress TCC prompts)
approve-daemon:
	@echo "→ Opening System Settings → Privacy & Security → Full Disk Access"
	@echo "  Add 'Self Driving Wiki' (from /Applications) to suppress the"
	@echo "  'wikid would like to access data from other apps' prompt."
	@echo "  This is a ONE-TIME step — the grant persists across rebuilds."
	@open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------

clean:
	rm -rf build .build $(DIST_DIR)
	@echo "✓ removed build/, .build/, and $(DIST_DIR)/"

# ---------------------------------------------------------------------------
# Release pipeline: sign → zip-notary → notarize → staple → zip-release →
# checksum → verify-release. The two-zip dance is on purpose: Apple's notary
# service operates on a zip; stapling writes the ticket back into the .app;
# the zip we distribute must be a fresh one taken AFTER stapling so offline
# first-launch Gatekeeper finds the ticket inside the bundle.
#
#   git tag v0.1.0 && make dist
# ---------------------------------------------------------------------------

dist: check-version clean release sign zip-notary notarize staple zip-release checksum verify-release
	@echo "✓ release artifact ready: $(RELEASE_ZIP)"
	@echo "  next: make github-release   (or upload $(RELEASE_ZIP) manually)"

check-version:
	@if [ -z "$(VERSION)" ]; then \
	  echo "✗ VERSION is empty — no exact vX.Y.Z git tag at HEAD and no VERSION file."; \
	  echo "  Tag the release first:   git tag v0.1.0 && make dist"; \
	  echo "  Or override:             make dist VERSION=0.1.0"; \
	  exit 1; \
	fi
	@if [ -z "$(GIT_TAG_VERSION)" ]; then \
	  echo "✗ make dist requires an exact 'vX.Y.Z' git tag at HEAD."; \
	  echo "  HEAD currently has no matching tag; VERSION=$(VERSION) came from a fallback."; \
	  echo "  Tag the release first:   git tag v$(VERSION) && make dist"; \
	  exit 1; \
	fi
	@echo "→ release version $(VERSION)"

notary-setup:
	@command -v xcrun >/dev/null 2>&1 || { echo "✗ xcrun not found — install Xcode or the Command Line Tools"; exit 1; }
	@if [ ! -t 0 ]; then \
	  echo "✗ make notary-setup is interactive — run it in a real terminal,"; \
	  echo "  not from an editor / agent shell (it prompts for your password)."; \
	  echo ""; \
	  echo "  Steps once you're in a terminal:"; \
	  echo "    1. Create an App-Specific Password at https://appleid.apple.com → Sign-In and Security."; \
	  echo "    2. Run: make notary-setup APPLE_ID=you@example.com"; \
	  echo "    3. Paste the App-Specific Password when prompted."; \
	  echo ""; \
	  echo "  The password is stored in the login keychain under profile '$(NOTARY_PROFILE)'."; \
	  exit 1; \
	fi
	@echo "→ storing notary credentials in keychain profile '$(NOTARY_PROFILE)' (team $(TEAM_ID))"
	xcrun notarytool store-credentials "$(NOTARY_PROFILE)" \
	  --team-id "$(TEAM_ID)" \
	  $(if $(APPLE_ID),--apple-id "$(APPLE_ID)",)
	@echo "✓ stored. 'make dist' / 'make notarize' will use profile '$(NOTARY_PROFILE)'."

sign: release
	@if [ -z "$(CERT_NAME)" ]; then echo "✗ CERT_NAME required"; exit 1; fi
	@security find-certificate -c "Developer ID Certification Authority" >/dev/null 2>&1 \
	  || security find-certificate -c "Developer ID Certification Authority" /Library/Keychains/System.keychain >/dev/null 2>&1 \
	  || { \
	    echo "✗ Apple's 'Developer ID Certification Authority' intermediate is missing from your keychains."; \
	    echo "  codesign can't build a chain to a trusted root without it."; \
	    echo "  Fix: download the G2 intermediate from https://www.apple.com/certificateauthority/"; \
	    echo "  and double-click the .cer to install it into your login keychain."; \
	    exit 1; \
	  }
	@echo "→ signing $(APP) as $(CERT_NAME)"
	codesign --force --options runtime --timestamp \
	  --entitlements "$(ENTITLEMENTS)" \
	  --sign "$(CERT_NAME)" "$(APP)"
	codesign --verify --strict --verbose=2 "$(APP)"

zip-notary: sign
	@mkdir -p "$(DIST_DIR)"
	rm -f "$(NOTARY_ZIP)"
	ditto -c -k --keepParent "$(APP)" "$(NOTARY_ZIP)"
	@echo "✓ wrote $(NOTARY_ZIP)"

notarize: zip-notary
	@if [ -z "$(NOTARY_PROFILE)" ]; then \
	  echo "✗ NOTARY_PROFILE is empty. Run 'make notary-setup' once first."; \
	  exit 1; \
	fi
	@echo "→ submitting $(NOTARY_ZIP) via profile '$(NOTARY_PROFILE)' (a few minutes)"
	xcrun notarytool submit "$(NOTARY_ZIP)" \
	  --keychain-profile "$(NOTARY_PROFILE)" \
	  --wait

staple: notarize
	xcrun stapler staple "$(APP)"
	xcrun stapler validate "$(APP)"

zip-release: staple
	rm -f "$(RELEASE_ZIP)"
	ditto -c -k --keepParent "$(APP)" "$(RELEASE_ZIP)"
	@echo "✓ wrote $(RELEASE_ZIP)"

checksum: zip-release
	cd "$(DIST_DIR)" && shasum -a 256 "$$(basename "$(RELEASE_ZIP)")" > "$$(basename "$(RELEASE_ZIP)").sha256"
	@echo "✓ wrote $(RELEASE_ZIP).sha256"

verify-release: zip-release
	spctl --assess --type execute --verbose "$(APP)"
	codesign --verify --deep --strict --verbose=2 "$(APP)"

github-release:
	@if ! command -v gh >/dev/null 2>&1; then echo "✗ gh CLI not installed (brew install gh)"; exit 1; fi
	@if [ -z "$(VERSION)" ]; then echo "✗ VERSION required (tag or override)"; exit 1; fi
	@if [ ! -f "$(RELEASE_ZIP)" ]; then echo "✗ $(RELEASE_ZIP) not found — run make dist first"; exit 1; fi
	@if [ ! -f "$(RELEASE_ZIP).sha256" ]; then echo "✗ $(RELEASE_ZIP).sha256 not found — run make dist first"; exit 1; fi
	gh release create "v$(VERSION)" \
	  "$(RELEASE_ZIP)" \
	  "$(RELEASE_ZIP).sha256" \
	  --title "$(APP_NAME) $(VERSION)" \
	  $(if $(NOTES_FILE),--notes-file "$(NOTES_FILE)",--generate-notes)
	@echo "✓ published v$(VERSION)"
