# Self Driving Wiki — native macOS SwiftUI wiki with a filesystem projection
#
# Quick start:
#   make           # debug-builds via SwiftPM into ./build/Self Driving Wiki.app
#   make run       # build + launch
#   make check     # compile only, no bundling/signing (agent / CI gate)
#   make install   # copy to /Applications/ and register with LaunchServices
#   make help      # full target list
#
# Build is driven by `swift build` + ./build.sh — NO Xcode IDE, NO
# xcodebuild, NO XcodeGen. Xcode is only a toolchain provider (swift /
# codesign / notarytool / stapler). The release/notarization pipeline is
# wired but unused until v0 ships; `make dist` produces a signed-and-stapled
# release zip.

CONFIG       := debug
APP_NAME      := Self Driving Wiki
APP          := build/$(APP_NAME).app
INSTALLED_APP := /Applications/$(APP_NAME).app
LEGACY_APP    := /Applications/WikiFS.app
EXT_NAME      := WikiFSFileProvider

# Per-developer signing config (gitignored shell file; see
# signing/local.config.example). build.sh sources it directly; here we extract
# individual values, falling back to the upstream author's defaults when absent.
#   $(call cfg,VARNAME) → value from signing/local.config, or empty.
LOCAL_CONFIG := signing/local.config
cfg = $(shell . $(LOCAL_CONFIG) >/dev/null 2>&1 && printf '%s' "$$$(1)")

EXT_BUNDLE_ID := $(or $(call cfg,EXT_BUNDLE_ID),org.sockpuppet.WikiFS.FileProvider)
LSREGISTER   := /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister
PLUGINKIT    := pluginkit
MIN_MACOS    := 14
MIN_SWIFT    := 6.0

# Generated by build.sh from the resolved identifiers (not a committed file).
ENTITLEMENTS  := build/WikiFS.entitlements

# Agent-prompt codegen (prompts/*.md → a checked-in Swift file). Defined here,
# BEFORE the build/check/test/release rules, so those rules' prerequisites can
# reference $(GENERATED_PROMPTS); Make expands prerequisites top-to-bottom. The
# timestamp file rule and the `prompts` / `check-prompts` targets live below.
PROMPT_SOURCES    := $(wildcard prompts/*.md)
PROMPT_GENERATOR  := tools/promptgen/main.swift
GENERATED_PROMPTS := Sources/WikiFSCore/GeneratedPrompts.swift

# Version codegen (git state → a checked-in Swift file with appVersion, gitSHA,
# gitCommitCount, buildVersion). Same pattern as promptgen above: the file is
# checked in so bare `swift build` works; `make version` regenerates it from the
# current git state. CI runs `make check-version-gen` to fail on drift. The
# generator only writes when content actually changes, so being a .PHONY prereq
# of build/check/test/release doesn't force recompilation on every invocation.
VERSIONGEN_SCRIPT  := tools/versiongen/main.swift
GENERATED_VERSION  := Sources/WikiFSCore/GeneratedVersion.swift

# ---------------------------------------------------------------------------
# Release variables
# ---------------------------------------------------------------------------
# Version is resolved in this order:
#   1. VERSION=... on the command line (one-off testing, no tag needed).
#   2. An exact `vX.Y.Z` git tag at HEAD (the canonical `make dist` path).
#   3. The VERSION file at the repo root (so contributors can preview the
#      pipeline without tagging first; `make dist` still requires the tag).
GIT_TAG_VERSION := $(shell git describe --tags --exact-match --match 'v[0-9]*' 2>/dev/null | sed 's/^v//')
FILE_VERSION    := $(shell test -f VERSION && sed -n '1p' VERSION | tr -d '[:space:]')
VERSION         ?= $(or $(GIT_TAG_VERSION),$(FILE_VERSION))

DIST_DIR      := dist
NOTARY_ZIP    := $(DIST_DIR)/$(APP_NAME)-$(VERSION)-notary.zip
RELEASE_ZIP   := $(DIST_DIR)/$(APP_NAME)-$(VERSION)-macos.zip

# Dev signing identity (used by ./build.sh). Falls back to ad-hoc ("-") if
# the named identity is missing — fine for `make run` on your own machine.
DEV_IDENTITY  ?= $(or $(call cfg,DEV_IDENTITY),Apple Development: Thomas Ptacek (7F2QE7P59D))

# Distribution signing. Developer ID + hardened runtime + notarization.
TEAM_ID       ?= $(or $(call cfg,TEAM_ID),KK7E9G89GW)
CERT_NAME     ?= $(or $(call cfg,CERT_NAME),Developer ID Application: Thomas Ptacek ($(TEAM_ID)))

# Notarization credentials profile name. Populate once with
# `make notary-setup` (interactive; never puts the password on the cmdline).
NOTARY_PROFILE ?= wikifs-notary

PROVISION_PROFILE ?=
NOTES_FILE       ?=

.PHONY: all deps build check test release run reload clean install uninstall register help prune-provider-registrations \
        check-version notary-setup sign zip-notary notarize staple zip-release \
        checksum verify-release dist github-release print-version icon prompts check-prompts \
        version check-version-gen

all: build

help:
	@echo "Build:"
	@echo "  make / build      Build $(CONFIG) into ./$(APP)  (default)"
	@echo "                    (also builds ./build/wikictl + embeds it in the app bundle)"
	@echo "  check             Compile only (swift build) — no bundle/sign; CI/agent gate"
	@echo "  test              Run the SwiftPM test suite"
	@echo "  prompts           Regenerate Sources/WikiFSCore/GeneratedPrompts.swift from prompts/*.md"
	@echo "  check-prompts     CI gate — fail if GeneratedPrompts.swift is stale"
	@echo "  version           Regenerate Sources/WikiFSCore/GeneratedVersion.swift from git state"
	@echo "  check-version-gen CI gate — fail if GeneratedVersion.swift is stale"
	@echo "  release           Build release into ./$(APP)"
	@echo "  run               Install to /Applications and launch $(APP_NAME)"
	@echo "  reload            Like run, but forces the File Provider domain to reset —"
	@echo "                    use after changing FileProvider rendering (Projection.swift,"
	@echo "                    PageMarkdownFormat, RelativeLinkRewriter, …); the daemon"
	@echo "                    caches materialized files by data version, so a rendering-only"
	@echo "                    change is otherwise invisible until content is next edited"
	@echo "  clean             Remove ./build/ ./.build/ ./dist/"
	@echo "  deps              Verify build prerequisites (auto-run before build)"
	@echo ""
	@echo "Local install:"
	@echo "  install           Copy $(APP_NAME).app to /Applications/ and register app + File Provider"
	@echo "  uninstall         Remove /Applications/$(APP_NAME).app"
	@echo "  register          Same as install; File Provider must run from /Applications"
	@echo ""
	@echo "Release pipeline (require an exact 'vX.Y.Z' git tag):"
	@echo "  notary-setup      One-time: store notary creds in keychain ($(NOTARY_PROFILE))"
	@echo "  dist              Build → sign → notarize → staple → zip → checksum"
	@echo "  github-release    Upload \$$(RELEASE_ZIP) + .sha256 to a GitHub release"
	@echo "  sign              codesign Developer ID + hardened runtime + timestamp"
	@echo "  notarize          Submit to Apple (keychain profile $(NOTARY_PROFILE))"
	@echo "  staple            xcrun stapler staple"
	@echo "  verify-release    spctl + codesign sanity-check the bundle"
	@echo "  print-version     Print resolved release VERSION"
	@echo ""
	@echo "  help              Show this message"

# ---------------------------------------------------------------------------
# Prerequisite checks
# ---------------------------------------------------------------------------

deps:
	@echo "→ Checking build prerequisites..."
	@OS_VERSION=$$(sw_vers -productVersion 2>/dev/null); \
	if [ -z "$$OS_VERSION" ]; then \
	  echo "  ✗ Could not detect macOS version. $(APP_NAME) only builds on macOS."; exit 1; \
	fi; \
	OS_MAJOR=$$(echo $$OS_VERSION | cut -d. -f1); \
	if [ $$OS_MAJOR -lt $(MIN_MACOS) ]; then \
	  echo "  ✗ macOS $$OS_VERSION — $(APP_NAME) requires macOS $(MIN_MACOS).0 or newer."; exit 1; \
	fi; \
	echo "  ✓ macOS $$OS_VERSION"
	@command -v swift >/dev/null 2>&1 || { \
	  echo "  ✗ swift not on PATH. Install Xcode (App Store) or the Swift toolchain"; \
	  echo "    from https://swift.org/install/macos/, then re-run."; exit 1; }
	@SW_LINE=$$(swift --version 2>&1 | head -1); \
	echo "  ✓ $$SW_LINE"
	@[ -f Package.swift ] || { echo "  ✗ Package.swift not found. Run make from the repo root."; exit 1; }
	@echo "  ✓ Package.swift present"
	@[ -x ./build.sh ] || { echo "  ✗ ./build.sh missing or not executable."; exit 1; }
	@echo "  ✓ build.sh present"
	@echo "→ Prerequisites OK."

# ---------------------------------------------------------------------------
# Build (delegates to ./build.sh: swift build + bundle + codesign)
# ---------------------------------------------------------------------------

ICON_SCRIPT := scripts/make-icon.swift
APP_ICON    := build/AppIcon.icns

# App icon: regenerated when the script changes. The script renders a white
# `books.vertical.fill` SF Symbol on a blue→indigo squircle at every macOS
# icon size; iconutil packages them. Output: build/AppIcon.icns, copied into
# the .app bundle by build.sh.
$(APP_ICON): $(ICON_SCRIPT)
	@mkdir -p build
	@swift $(ICON_SCRIPT)
	@iconutil -c icns build/AppIcon.iconset -o $(APP_ICON)
	@echo "✓ $(APP_ICON)"

icon: $(APP_ICON)

build: deps $(APP_ICON) $(GENERATED_PROMPTS) version
	SIGN_IDENTITY="$(DEV_IDENTITY)" PROVISION_PROFILE="$(PROVISION_PROFILE)" ./build.sh $(CONFIG)

release: deps $(APP_ICON) $(GENERATED_PROMPTS) version
	SIGN_IDENTITY="$(DEV_IDENTITY)" PROVISION_PROFILE="$(PROVISION_PROFILE)" ./build.sh release

# Compile-only gate — no .app, no signing. CI / agent verification.
check: deps $(GENERATED_PROMPTS) version
	swift build -c $(CONFIG)
	@echo "✓ compiles ($(CONFIG))"

# Run the test suite.
test: deps $(GENERATED_PROMPTS) version
	swift test
	@echo "✓ tests pass"

# ---------------------------------------------------------------------------
# Agent prompts (prompts/*.md → Sources/WikiFSCore/GeneratedPrompts.swift)
# ---------------------------------------------------------------------------

# The checked-in Swift constants are REGENERATED from the .md sources whenever a
# prompt or the generator changes — the timestamp-based file rule below is a
# prerequisite of `build`/`check`/`test`/`release`, so `make`, `make install`,
# and `make test` never compile stale prompts. (Bare `swift build` / `swift
# test` bypass make and do NOT regenerate — run `make prompts` after editing a
# .md if you're driving swift directly.) `make check-prompts` remains the CI
# authority for "is the COMMITTED file fresh."
$(GENERATED_PROMPTS): $(PROMPT_SOURCES) $(PROMPT_GENERATOR)
	swift tools/promptgen/main.swift

# Convenience alias — regenerates only if a .md or the generator is newer.
prompts: $(GENERATED_PROMPTS)

# CI gate — fail if the checked-in GeneratedPrompts.swift is stale vs the .md
# sources. Regenerates to stdout and diffs; exits non-zero on drift.
check-prompts: ## CI gate — fail if GeneratedPrompts.swift is stale vs prompts/*.md
	@tmp=$$(mktemp); trap 'rm -f $$tmp' EXIT; \
	swift tools/promptgen/main.swift --stdout > $$tmp; \
	if ! diff -u Sources/WikiFSCore/GeneratedPrompts.swift $$tmp; then \
		echo ">> GeneratedPrompts.swift is stale. Run 'make prompts' and commit." >&2; exit 1; \
	fi


# Version codegen — regenerate Sources/WikiFSCore/GeneratedVersion.swift from
# the current git state (tag/VERSION file → appVersion; SHA + commit count →
# buildVersion). Always runs; the generator skips writing if content is
# unchanged, so this doesn't force recompilation on every make invocation.
version:
	@swift $(VERSIONGEN_SCRIPT)

# CI gate — fail if the checked-in GeneratedVersion.swift is stale vs git.
check-version-gen:
	@tmp=$$(mktemp); trap 'rm -f $$tmp' EXIT; \
	swift $(VERSIONGEN_SCRIPT) --stdout > $$tmp; \
	if ! diff -u Sources/WikiFSCore/GeneratedVersion.swift $$tmp; then \
		echo ">> GeneratedVersion.swift is stale. Run 'make version' and commit." >&2; exit 1; \
	fi

print-version:
	@echo "VERSION=$(VERSION)"
	@echo "  git tag at HEAD: $(if $(GIT_TAG_VERSION),$(GIT_TAG_VERSION),(none))"
	@echo "  VERSION file:    $(if $(FILE_VERSION),$(FILE_VERSION),(missing))"
	@echo "  git SHA:         $$(git rev-parse --short HEAD 2>/dev/null || echo '(unknown)')"
	@echo "  commit count:    $$(git rev-list --count HEAD 2>/dev/null || echo '?')"
	@echo "  build version:   $$(git rev-list --count HEAD 2>/dev/null || echo '0')-$$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

# ---------------------------------------------------------------------------
# Run / install / register
# ---------------------------------------------------------------------------

run: install
	open "$(INSTALLED_APP)"

# `reload` — like `run`, but forces every registered File Provider domain to be
# removed and re-added before it mounts again.
#
# Why this exists: fileproviderd caches each materialized file's bytes keyed
# by the DATA version the extension reports (page.version / chat.updatedAt /
# the whole-DB changeToken — see Projection.swift's `pageFileNode` etc.), NOT
# by the extension's own build/code version. So a rebuild that changes how a
# file is RENDERED (e.g. #216's [[wikilink]] → relative-Markdown-link rewrite)
# is invisible to already-materialized files on disk: the daemon sees the same
# reported version it already cached and never calls back into the extension
# for fresh bytes. A plain `make install`/`run` — even a from-scratch rebuild —
# does not fix this; the stale copies live in fileproviderd's cache, not the
# app bundle. There is no `fileproviderctl` evict/reimport subcommand on this
# OS to force it from the shell, and a raw `rm` on a mounted file round-trips
# through the (read-only) extension's `deleteItem` and is rejected.
#
# The one CLI-drivable fix is the app's own `WIKIFS_REENUMERATE=1` hatch
# (FileProviderSpike.swift `registerDomain`): read once at launch, it calls
# `NSFileProviderManager.remove(domain)` for each wiki before re-adding it —
# tearing down and rebuilding the whole projection, which forces a full
# re-fetch. `open --env` (macOS 14+) sets that var for the freshly-launched
# process; a plain `open` does not propagate shell environment into the
# relaunch, so this can't just be `WIKIFS_REENUMERATE=1 open ...`. Both the
# app and extension processes are killed first so `-n` (new instance) doesn't
# leave a stale, non-reset instance running alongside the fresh one.
#
# This is a one-shot manual hatch for local dev; it is deliberately NOT the
# default `run`/`install` behavior because a full domain reset re-downloads
# everything and would slow down routine iteration unrelated to rendering
# changes. The permanent, no-flag-needed fix for a SHIPPED rendering-contract
# change is bumping `FileProviderSpike.currentSchemaVersion`, which resets
# every user's domain automatically on next launch (see its doc comment) —
# use `reload` here to verify, then decide separately whether the change
# warrants that bump.
reload: install
	@pkill -f "$(INSTALLED_APP)/Contents/MacOS/$(APP_NAME)" 2>/dev/null && echo "✓ killed running $(APP_NAME)" || true
	@pkill -f "$(EXT_NAME).appex" 2>/dev/null && echo "✓ killed stale $(EXT_NAME) process" || true
	@sleep 1
	open --env WIKIFS_REENUMERATE=1 -n "$(INSTALLED_APP)"
	@echo "✓ relaunched $(APP_NAME) with WIKIFS_REENUMERATE=1 — File Provider domain(s) will reset on this launch"

install: build prune-provider-registrations
	@if [ ! -d "$(APP)" ]; then echo "✗ $(APP) missing — build failed?"; exit 1; fi
	@pkill -f "$(EXT_NAME).appex" 2>/dev/null && echo "✓ killed stale $(EXT_NAME) process" || true
	rm -rf "$(INSTALLED_APP)"
	cp -R "$(APP)" /Applications/
	@echo "✓ copied to $(INSTALLED_APP)"
	$(LSREGISTER) -f "$(INSTALLED_APP)"
	$(PLUGINKIT) -a "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex"
	$(PLUGINKIT) -e use -i "$(EXT_BUNDLE_ID)" -p com.apple.fileprovider-nonui >/dev/null 2>&1 || true
	@for attempt in 1 2 3; do \
	  if $(PLUGINKIT) -m -p com.apple.fileprovider-nonui -i "$(EXT_BUNDLE_ID)" -A -D -vvv 2>/dev/null \
	    | grep -Fq "Path = $(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex"; then \
	    exit 0; \
	  fi; \
	  sleep 1; \
	done; \
	echo "✗ $(EXT_BUNDLE_ID) did not register at $(INSTALLED_APP)" >&2; \
	$(PLUGINKIT) -m -p com.apple.fileprovider-nonui -i "$(EXT_BUNDLE_ID)" -A -D -vvv 2>&1 || true; \
	exit 1
	@echo "✓ registered $(INSTALLED_APP) and $(EXT_BUNDLE_ID)"

prune-provider-registrations:
	@for appex in \
	  "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "$(APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "$(LEGACY_APP)/Contents/PlugIns/$(EXT_NAME).appex" \
	  "build/WikiFS.app/Contents/PlugIns/$(EXT_NAME).appex" \
	  "/private/tmp/Wtest.app/Contents/PlugIns/$(EXT_NAME).appex"; do \
	  if [ -d "$$appex" ]; then $(PLUGINKIT) -r "$$appex" >/dev/null 2>&1 || true; fi; \
	done
	@for app in "$(APP)" "$(LEGACY_APP)" "build/WikiFS.app" "/private/tmp/Wtest.app"; do \
	  if [ -d "$$app" ]; then $(LSREGISTER) -u "$$app" >/dev/null 2>&1 || true; fi; \
	done

uninstall:
	@if [ -d "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" ]; then \
	  $(PLUGINKIT) -r "$(INSTALLED_APP)/Contents/PlugIns/$(EXT_NAME).appex" >/dev/null 2>&1 || true; \
	fi
	@if [ -d "$(INSTALLED_APP)" ]; then \
	  rm -rf "$(INSTALLED_APP)" 2>/dev/null || sudo rm -rf "$(INSTALLED_APP)"; \
	  echo "✓ removed $(INSTALLED_APP)"; \
	else \
	  echo "  (no $(INSTALLED_APP) to remove)"; \
	fi

register: install

# ---------------------------------------------------------------------------
# wikid daemon — launchd install/uninstall (plans/multi-wiki-daemon.md Phase 1B)
# ---------------------------------------------------------------------------

WIKID_BIN := $(shell swift build --show-bin-path)/wikid
WIKID_PLIST := signing/com.selfdrivingwiki.wikid.plist
WIKID_PLIST_DST := $(HOME)/Library/LaunchAgents/com.selfdrivingwiki.wikid.plist

# Resolve the signing identity from signing/local.config (same as build.sh).
WIKID_SIGN_IDENTITY := $(shell grep '^DEV_IDENTITY=' signing/local.config 2>/dev/null | sed 's/DEV_IDENTITY=//; s/^"//; s/"$$//' || echo "-")
WIKID_SIGN_TEAM := $(shell grep '^TEAM_ID=' signing/local.config 2>/dev/null | sed 's/TEAM_ID=//; s/^"//; s/"$$//' || echo "")

.PHONY: install-daemon uninstall-daemon daemon-status

install-daemon: ## Install wikid as a launchd LaunchAgent (auto-starts on first XPC connection)
install-daemon:
	@echo "→ Building wikid…"
	@swift build --target wikid
	@echo "→ Codesigning wikid (identity: $(WIKID_SIGN_IDENTITY))…"
	@# Sign the binary with an identifier matching the mach service name so
	@# macOS TCC doesn't prompt on XPC connections. Falls back to ad-hoc (-).
	@codesign --force --timestamp=none --identifier com.selfdrivingwiki.wikid \
		--sign "$(WIKID_SIGN_IDENTITY)" "$(WIKID_BIN)" 2>/dev/null \
		|| codesign --force --timestamp=none --sign - "$(WIKID_BIN)"
	@# Also sign wikictl — it's the client connecting to the mach service.
	@codesign --force --timestamp=none --identifier com.selfdrivingwiki.wikictl \
		--sign "$(WIKID_SIGN_IDENTITY)" "$(dir $(WIKID_BIN))wikictl" 2>/dev/null \
		|| codesign --force --timestamp=none --sign - "$(dir $(WIKID_BIN))wikictl"
	@echo "→ Installing launchd plist…"
	@mkdir -p $(dir $(WIKID_PLIST_DST))
	@# Copy the plist template, then inject the binary path into a ProgramArguments array.
	@cp $(WIKID_PLIST) $(WIKID_PLIST_DST)
	@plutil -insert ProgramArguments -array -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST) 2>/dev/null || true
	@plutil -insert ProgramArguments.0 -string "$(WIKID_BIN)" -o $(WIKID_PLIST_DST) $(WIKID_PLIST_DST)
	@launchctl unload $(WIKID_PLIST_DST) 2>/dev/null || true
	@launchctl load $(WIKID_PLIST_DST)
	@echo "✓ wikid installed. It will auto-start when a client connects via XPC."
	@echo "  Binary: $(WIKID_BIN)"
	@echo "  Plist:  $(WIKID_PLIST_DST)"
	@echo "  Status: make daemon-status"

uninstall-daemon: ## Remove the wikid launchd agent
uninstall-daemon:
	@launchctl unload $(WIKID_PLIST_DST) 2>/dev/null || true
	@rm -f $(WIKID_PLIST_DST)
	@echo "✓ wikid uninstalled."

daemon-status: ## Show the wikid launchd agent status
daemon-status:
	@launchctl list | grep wikid || echo "wikid is not loaded."

# ---------------------------------------------------------------------------
# Clean
# ---------------------------------------------------------------------------

clean:
	rm -rf build .build $(DIST_DIR)
	@echo "✓ removed build/, .build/, and $(DIST_DIR)/"

# ---------------------------------------------------------------------------
# Release pipeline: sign → zip-notary → notarize → staple → zip-release →
# checksum → verify-release. The two-zip dance is on purpose: Apple's notary
# service operates on a zip; stapling writes the ticket back into the .app;
# the zip we distribute must be a fresh one taken AFTER stapling so offline
# first-launch Gatekeeper finds the ticket inside the bundle.
#
#   git tag v0.1.0 && make dist
# ---------------------------------------------------------------------------

dist: check-version clean release sign zip-notary notarize staple zip-release checksum verify-release
	@echo "✓ release artifact ready: $(RELEASE_ZIP)"
	@echo "  next: make github-release   (or upload $(RELEASE_ZIP) manually)"

check-version:
	@if [ -z "$(VERSION)" ]; then \
	  echo "✗ VERSION is empty — no exact vX.Y.Z git tag at HEAD and no VERSION file."; \
	  echo "  Tag the release first:   git tag v0.1.0 && make dist"; \
	  echo "  Or override:             make dist VERSION=0.1.0"; \
	  exit 1; \
	fi
	@if [ -z "$(GIT_TAG_VERSION)" ]; then \
	  echo "✗ make dist requires an exact 'vX.Y.Z' git tag at HEAD."; \
	  echo "  HEAD currently has no matching tag; VERSION=$(VERSION) came from a fallback."; \
	  echo "  Tag the release first:   git tag v$(VERSION) && make dist"; \
	  exit 1; \
	fi
	@echo "→ release version $(VERSION)"

notary-setup:
	@command -v xcrun >/dev/null 2>&1 || { echo "✗ xcrun not found — install Xcode or the Command Line Tools"; exit 1; }
	@if [ ! -t 0 ]; then \
	  echo "✗ make notary-setup is interactive — run it in a real terminal,"; \
	  echo "  not from an editor / agent shell (it prompts for your password)."; \
	  echo ""; \
	  echo "  Steps once you're in a terminal:"; \
	  echo "    1. Create an App-Specific Password at https://appleid.apple.com → Sign-In and Security."; \
	  echo "    2. Run: make notary-setup APPLE_ID=you@example.com"; \
	  echo "    3. Paste the App-Specific Password when prompted."; \
	  echo ""; \
	  echo "  The password is stored in the login keychain under profile '$(NOTARY_PROFILE)'."; \
	  exit 1; \
	fi
	@echo "→ storing notary credentials in keychain profile '$(NOTARY_PROFILE)' (team $(TEAM_ID))"
	xcrun notarytool store-credentials "$(NOTARY_PROFILE)" \
	  --team-id "$(TEAM_ID)" \
	  $(if $(APPLE_ID),--apple-id "$(APPLE_ID)",)
	@echo "✓ stored. 'make dist' / 'make notarize' will use profile '$(NOTARY_PROFILE)'."

sign: release
	@if [ -z "$(CERT_NAME)" ]; then echo "✗ CERT_NAME required"; exit 1; fi
	@security find-certificate -c "Developer ID Certification Authority" >/dev/null 2>&1 \
	  || security find-certificate -c "Developer ID Certification Authority" /Library/Keychains/System.keychain >/dev/null 2>&1 \
	  || { \
	    echo "✗ Apple's 'Developer ID Certification Authority' intermediate is missing from your keychains."; \
	    echo "  codesign can't build a chain to a trusted root without it."; \
	    echo "  Fix: download the G2 intermediate from https://www.apple.com/certificateauthority/"; \
	    echo "  and double-click the .cer to install it into your login keychain."; \
	    exit 1; \
	  }
	@echo "→ signing $(APP) as $(CERT_NAME)"
	codesign --force --options runtime --timestamp \
	  --entitlements "$(ENTITLEMENTS)" \
	  --sign "$(CERT_NAME)" "$(APP)"
	codesign --verify --strict --verbose=2 "$(APP)"

zip-notary: sign
	@mkdir -p "$(DIST_DIR)"
	rm -f "$(NOTARY_ZIP)"
	ditto -c -k --keepParent "$(APP)" "$(NOTARY_ZIP)"
	@echo "✓ wrote $(NOTARY_ZIP)"

notarize: zip-notary
	@if [ -z "$(NOTARY_PROFILE)" ]; then \
	  echo "✗ NOTARY_PROFILE is empty. Run 'make notary-setup' once first."; \
	  exit 1; \
	fi
	@echo "→ submitting $(NOTARY_ZIP) via profile '$(NOTARY_PROFILE)' (a few minutes)"
	xcrun notarytool submit "$(NOTARY_ZIP)" \
	  --keychain-profile "$(NOTARY_PROFILE)" \
	  --wait

staple: notarize
	xcrun stapler staple "$(APP)"
	xcrun stapler validate "$(APP)"

zip-release: staple
	rm -f "$(RELEASE_ZIP)"
	ditto -c -k --keepParent "$(APP)" "$(RELEASE_ZIP)"
	@echo "✓ wrote $(RELEASE_ZIP)"

checksum: zip-release
	cd "$(DIST_DIR)" && shasum -a 256 "$$(basename "$(RELEASE_ZIP)")" > "$$(basename "$(RELEASE_ZIP)").sha256"
	@echo "✓ wrote $(RELEASE_ZIP).sha256"

verify-release: zip-release
	spctl --assess --type execute --verbose "$(APP)"
	codesign --verify --deep --strict --verbose=2 "$(APP)"

github-release:
	@if ! command -v gh >/dev/null 2>&1; then echo "✗ gh CLI not installed (brew install gh)"; exit 1; fi
	@if [ -z "$(VERSION)" ]; then echo "✗ VERSION required (tag or override)"; exit 1; fi
	@if [ ! -f "$(RELEASE_ZIP)" ]; then echo "✗ $(RELEASE_ZIP) not found — run make dist first"; exit 1; fi
	@if [ ! -f "$(RELEASE_ZIP).sha256" ]; then echo "✗ $(RELEASE_ZIP).sha256 not found — run make dist first"; exit 1; fi
	gh release create "v$(VERSION)" \
	  "$(RELEASE_ZIP)" \
	  "$(RELEASE_ZIP).sha256" \
	  --title "$(APP_NAME) $(VERSION)" \
	  $(if $(NOTES_FILE),--notes-file "$(NOTES_FILE)",--generate-notes)
	@echo "✓ published v$(VERSION)"
