import Foundation

// pattern: Functional Core

/// An opaque, per-session secret. It is generated by the host and is never
/// exposed to package page code; the isolated broker adds it after postMessage.
public struct RendererSessionCapability: RawRepresentable, Hashable, Sendable, Codable {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
}

public struct RendererBridgeRequestID: RawRepresentable, Hashable, Sendable, Codable {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
}

public enum RendererBridgeMethod: String, Codable, Sendable {
    case inputRead = "input.read"
}

/// The only bridge input targets. A page cannot name a source, file path, URL,
/// or arbitrary artifact; it can only ask for the pin selected by its session.
public enum RendererBridgeInput: Codable, Equatable, Sendable {
    case source(versionID: SourceVersionID)
    case markdown(versionID: SourceMarkdownVersionID)
}

public struct RendererBridgeRequest: Codable, Equatable, Sendable {
    public let id: RendererBridgeRequestID
    public let method: RendererBridgeMethod
    public let capability: RendererSessionCapability
    public let input: RendererBridgeInput

    public init(id: RendererBridgeRequestID, method: RendererBridgeMethod, capability: RendererSessionCapability, input: RendererBridgeInput) {
        self.id = id
        self.method = method
        self.capability = capability
        self.input = input
    }
}

/// Page-visible envelope. The isolated broker converts this to a native request
/// and injects the capability, so package code cannot read or replay the token.
public struct RendererBridgePageRequest: Codable, Equatable, Sendable {
    public let id: RendererBridgeRequestID
    public let method: RendererBridgeMethod
    public let input: RendererBridgeInput

    public init(id: RendererBridgeRequestID, method: RendererBridgeMethod, input: RendererBridgeInput) {
        self.id = id
        self.method = method
        self.input = input
    }
}

public struct RendererBridgeInputPayload: Codable, Equatable, Sendable {
    public let mimeType: String
    public let bytes: Data
    public init(mimeType: String, bytes: Data) { self.mimeType = mimeType; self.bytes = bytes }
}

public struct RendererBridgeResponse: Codable, Equatable, Sendable {
    public let id: RendererBridgeRequestID
    public let payload: RendererBridgeInputPayload
    public init(id: RendererBridgeRequestID, payload: RendererBridgeInputPayload) { self.id = id; self.payload = payload }
}

public enum RendererBridgeEnvelope {
    public static func encode(_ request: RendererBridgeRequest) throws -> Data { try JSONEncoder().encode(request) }
    public static func decodeRequest(from data: Data) throws -> RendererBridgeRequest { try JSONDecoder().decode(RendererBridgeRequest.self, from: data) }
    public static func decodePageRequest(from data: Data) throws -> RendererBridgePageRequest { try JSONDecoder().decode(RendererBridgePageRequest.self, from: data) }
    public static func encode(_ response: RendererBridgeResponse) throws -> Data { try JSONEncoder().encode(response) }
}

public struct RendererBridgeAuthorizationContext: Equatable, Sendable {
    public let sessionID: RendererSessionID
    public let windowID: UUID
    public let frameID: UUID
    public let mainFrameID: UUID

    public init(sessionID: RendererSessionID, windowID: UUID, frameID: UUID, mainFrameID: UUID) {
        self.sessionID = sessionID; self.windowID = windowID; self.frameID = frameID; self.mainFrameID = mainFrameID
    }
}

public enum RendererBridgeAuthorizationError: Error, Equatable, Sendable {
    case malformedEnvelope, oversizedEnvelope, capabilityMismatch, wrongSession, wrongWindow, nonMainFrame
    case sessionNotReady, sessionClosed, invalidRequestID, duplicateRequestID, replayCapacityExceeded
    case unauthorizedInput, oversizedPayload, unavailablePinnedInput
}

/// Session-local authorization gate. Every session has an independent replay
/// set, expected window, and capability binding.
public struct RendererBridgeAuthorizer: Sendable {
    private let capability: RendererSessionCapability
    private let sessionID: RendererSessionID?
    private let windowID: UUID?
    private let authorizedInput: RendererBridgeInput?
    private var seenRequestIDs: Set<RendererBridgeRequestID> = []

    public init(capability: RendererSessionCapability, sessionID: RendererSessionID? = nil, windowID: UUID? = nil, authorizedInput: RendererBridgeInput? = nil) {
        self.capability = capability; self.sessionID = sessionID; self.windowID = windowID; self.authorizedInput = authorizedInput
    }

    public mutating func authorize(envelope: Data, sessionIsReady: Bool) throws -> RendererBridgeRequest {
        try authorize(envelope: envelope, context: nil, sessionIsReady: sessionIsReady, sessionIsClosed: false)
    }

    public mutating func authorize(envelope: Data, context: RendererBridgeAuthorizationContext?, sessionIsReady: Bool, sessionIsClosed: Bool) throws -> RendererBridgeRequest {
        guard envelope.count <= WikiAppWebViewPolicy.maximumBridgeMessageByteCount else { throw RendererBridgeAuthorizationError.oversizedEnvelope }
        guard sessionIsClosed == false else { throw RendererBridgeAuthorizationError.sessionClosed }
        guard sessionIsReady else { throw RendererBridgeAuthorizationError.sessionNotReady }
        let request: RendererBridgeRequest
        do { request = try RendererBridgeEnvelope.decodeRequest(from: envelope) }
        catch { throw RendererBridgeAuthorizationError.malformedEnvelope }
        guard request.capability == capability else { throw RendererBridgeAuthorizationError.capabilityMismatch }
        if let sessionID, let context {
            guard context.sessionID == sessionID else { throw RendererBridgeAuthorizationError.wrongSession }
            guard context.windowID == windowID else { throw RendererBridgeAuthorizationError.wrongWindow }
            guard context.frameID == context.mainFrameID else { throw RendererBridgeAuthorizationError.nonMainFrame }
        }
        guard authorizedInput == nil || request.input == authorizedInput else { throw RendererBridgeAuthorizationError.unauthorizedInput }
        let requestIDByteCount = request.id.rawValue.utf8.count
        guard requestIDByteCount > 0,
              requestIDByteCount <= WikiAppWebViewPolicy.maximumBridgeRequestIDByteCount
        else { throw RendererBridgeAuthorizationError.invalidRequestID }
        guard seenRequestIDs.count < WikiAppWebViewPolicy.maximumRetainedBridgeRequestIDs
        else { throw RendererBridgeAuthorizationError.replayCapacityExceeded }
        guard seenRequestIDs.insert(request.id).inserted else { throw RendererBridgeAuthorizationError.duplicateRequestID }
        return request
    }
}
