// tools/promptgen/main.swift
//
// Generates Sources/WikiFSCore/GeneratedPrompts.swift from prompts/*.md. Each
// .md file maps 1:1 to a Swift constant; the file's bytes are embedded VERBATIM
// inside an extended raw-string literal (#""" … """#) whose hash count
// auto-escalates so no escaping is ever needed (backticks, backslashes, "$",
// "\"", and "\(...)" all stay literal).
//
// Run:
//   swift tools/promptgen/main.swift          overwrite the generated file
//   swift tools/promptgen/main.swift --stdout  write to stdout (CI drift check)
//
// The normal `swift build` / `swift test` path NEVER invokes this — the
// generated file is checked in. CI runs `make check-prompts` to fail if the
// checked-in file is stale vs the .md sources.

import Foundation

// Single source of truth: .md filename (under prompts/) → generated constant
// name. Order is stable so the output diffs cleanly when a prompt is edited.
let entries: [(file: String, constant: String)] = [
    ("system-prompt-default.md",     "systemPromptDefault"),
    ("wiki-index-default.md",        "wikiIndexDefault"),
    ("ingest-write-rule.md",         "ingestWriteRule"),
    ("footnote-conclusions-rule.md", "footnoteConclusionsRule"),
    ("answer-citation-rule.md",      "answerCitationRule"),
    ("digester-prompt.md",           "digesterPrompt"),
    ("extraction-system.md",         "extractionSystem"),
    ("extraction-instruction.md",    "extractionInstruction"),
    ("source-reader-description.md", "sourceReaderDescription"),
    ("dont-rediscover-leaf.md",      "dontRediscoverLeaf"),
    ("wiki-tree-render.md",          "wikiTreeRender"),
]

// Resolve the repo root from this script's location (tools/promptgen/ → up 2).
// Works whether #file is absolute or relative-as-run-from-repo-root.
let scriptDir = URL(fileURLWithPath: #file).deletingLastPathComponent()
let repoRoot = scriptDir.deletingLastPathComponent().deletingLastPathComponent()
let promptsDir = repoRoot.appendingPathComponent("prompts")
let outputFile = repoRoot
    .appendingPathComponent("Sources")
    .appendingPathComponent("WikiFSCore")
    .appendingPathComponent("GeneratedPrompts.swift")

let toStdout = CommandLine.arguments.dropFirst().contains("--stdout")

func readPrompt(_ name: String) -> String {
    let url = promptsDir.appendingPathComponent(name)
    guard let data = try? Data(contentsOf: url),
          let body = String(data: data, encoding: .utf8)
    else {
        FileHandle.standardError.write(Data("promptgen: cannot read \(url.path)\n".utf8))
        exit(1)
    }
    return body
}

/// The number of `#` to use for a raw-string delimiter around `content`. A raw
/// string opened with N hashes is closed only by `"` `"` `"` followed by ≥N
/// hashes, so we need N strictly greater than the longest run of hashes that
/// immediately follows a `"` anywhere in the content. We also escalate by one
/// if the content ends with `"` (defensive — keeps a trailing quote from
/// sitting flush against the closing delimiter). Today's prompts need N = 1.
func delimiterCount(for content: String) -> Int {
    let chars = Array(content)
    var maxRun = 0
    var i = 0
    while i < chars.count {
        if chars[i] == "\"" {
            var run = 0
            var j = i + 1
            while j < chars.count && chars[j] == "#" { run += 1; j += 1 }
            if run > maxRun { maxRun = run }
            i = j
        } else {
            i += 1
        }
    }
    var n = max(maxRun + 1, 1)
    if chars.last == "\"" { n += 1 }
    return n
}

func rawWrap(_ content: String) -> String {
    let n = delimiterCount(for: content)
    let hashes = String(repeating: "#", count: n)
    // Multiline raw string: the opening `#"""` must be followed by a newline
    // (content begins on the next line), and the closing `"""#` must sit on
    // its own line. Swift strips exactly ONE newline immediately before the
    // closing delimiter, so we append an extra trailing newline that gets
    // stripped — leaving `content` byte-identical. The closing delimiter is at
    // column 0, so the per-line dedent is zero and content bytes are preserved
    // verbatim (a .md's leading indentation is significant).
    return "\(hashes)\"\"\"\n\(content)\n\"\"\"\(hashes)"
}

var out = """
// GENERATED BY tools/promptgen — DO NOT EDIT.
// Source: prompts/*.md  ·  Regenerate: `make prompts`
// Each constant holds the verbatim bytes of its .md source. The auto-escalating
// raw-string delimiters mean no content escaping is ever applied — edit the
// .md, run `make prompts`, commit both.

import Foundation

enum GeneratedPrompts {

"""

for entry in entries {
    let body = readPrompt(entry.file)
    out += "    static let \(entry.constant) = \(rawWrap(body))\n\n"
}

out += "}\n"

if toStdout {
    FileHandle.standardOutput.write(Data(out.utf8))
} else {
    do {
        try out.write(to: outputFile, atomically: true, encoding: .utf8)
        FileHandle.standardError.write(Data("promptgen: wrote \(outputFile.path)\n".utf8))
    } catch {
        FileHandle.standardError.write(Data("promptgen: cannot write \(outputFile.path): \(error)\n".utf8))
        exit(1)
    }
}
