// tools/versiongen/main.swift
//
// Generates Sources/WikiFSCore/GeneratedVersion.swift from git state at build
// time. Mirrors tools/promptgen/main.swift: the generated file is checked in so
// bare `swift build` works, and `make version` (a prerequisite of build/check/
// test/release) regenerates it. CI runs `make check-version-gen` to fail if the
// checked-in file is stale.
//
// Version scheme:
//   appVersion     — SemVer from an exact vX.Y.Z tag at HEAD, or the VERSION
//                    file, or "0.0.0" fallback. Goes into CFBundleShortVersionString.
//   gitSHA         — short SHA from `git rev-parse --short HEAD`.
//   gitCommitCount — monotone integer from `git rev-list --count HEAD`.
//   buildVersion   — "<count>-<sha>" (e.g. "423-abc1234"). Goes into CFBundleVersion.
//
// Run:
//   swift tools/versiongen/main.swift          overwrite the generated file
//   swift tools/versiongen/main.swift --stdout  write to stdout (CI drift check)
//
// The script only writes the file if content actually changed, so making it a
// .PHONY prerequisite of `build`/`check`/`test` doesn't force recompilation on
// every invocation — only when the version actually moves.

import Foundation

// MARK: - Git helpers

/// Run a shell command and return its trimmed stdout. Returns nil on failure.
func shell(_ command: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    process.arguments = ["sh", "-c", command]
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = Pipe() // swallow errors
    do {
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else { return nil }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
    } catch {
        return nil
    }
}

// MARK: - Resolve version components

/// SemVer from tag or VERSION file; "0.0.0" fallback. Treats empty git output
/// (e.g. `git describe` piped through `sed` exits 0 with no stdout) as a miss.
func resolveAppVersion() -> String {
    if let tag = shell("git describe --tags --exact-match --match 'v[0-9]*' 2>/dev/null | sed 's/^v//'"),
       !tag.isEmpty {
        return tag
    }
    if let fileVersion = shell("test -f VERSION && sed -n '1p' VERSION | tr -d '[:space:]'"),
       !fileVersion.isEmpty {
        return fileVersion
    }
    return "0.0.0"
}
let appVersion = resolveAppVersion()

/// Short SHA (e.g. "abc1234"). "unknown" if not in a git repo.
let gitSHA = shell("git rev-parse --short HEAD") ?? "unknown"

/// Monotone commit count. "0" if not in a git repo.
let gitCommitCount = shell("git rev-list --count HEAD") ?? "0"

/// Build identifier: "<count>-<sha>" (e.g. "423-abc1234").
let buildVersion = "\(gitCommitCount)-\(gitSHA)"

/// Full display string: "0.0.0 (423-abc1234)".
let fullVersionString = "\(appVersion) (\(buildVersion))"

// MARK: - Generate Swift source

let output = """
// Sources/WikiFSCore/GeneratedVersion.swift
//
// GENERATED by tools/versiongen/main.swift — DO NOT EDIT.
// Regenerate with: make version
//
// Version constants baked in at build time from git state. Accessible from both
// the app (WikiFS) and wikictl via the WikiFSCore dependency.

import Foundation

/// Build-time version constants resolved from git. Mirrors the Info.plist keys
/// written by build.sh (CFBundleShortVersionString, CFBundleVersion, WIKIGitSHA,
/// WIKIGitCommitCount, WIKIBuildVersion) so code and bundle stay in sync.
public enum GeneratedVersion {
    /// Marketing version (SemVer from tag or VERSION file, e.g. "0.5.0").
    /// Goes into CFBundleShortVersionString.
    public static let appVersion = \"\(appVersion)\"

    /// Short git SHA (e.g. "abc1234"). Goes into the WIKIGitSHA Info.plist key.
    public static let gitSHA = \"\(gitSHA)\"

    /// Git commit count — a monotone integer (e.g. "423"). Goes into
    /// WIKIGitCommitCount.
    public static let gitCommitCount = \"\(gitCommitCount)\"

    /// Build identifier: "<count>-<sha>" (e.g. "423-abc1234"). Goes into
    /// CFBundleVersion.
    public static let buildVersion = \"\(buildVersion)\"

    /// Full display string: "<appVersion> (<buildVersion>)" — e.g. "0.5.0 (423-abc1234)".
    public static let fullVersionString = \"\(fullVersionString)\"
}

"""

// MARK: - Write

let outputPath = "Sources/WikiFSCore/GeneratedVersion.swift"

let useStdout = CommandLine.arguments.contains("--stdout")
if useStdout {
    FileHandle.standardOutput.write(Data(output.utf8))
    exit(0)
}

let existingContent = (try? String(contentsOfFile: outputPath, encoding: .utf8)) ?? ""
if output == existingContent {
    // No change — skip writing to avoid touching the file's mtime (which would
    // trigger an unnecessary swift recompile).
    exit(0)
}

try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("✓ regenerated \(outputPath)")
