// Sources/WikiFSCore/GeneratedVersion.swift
//
// GENERATED by tools/versiongen/main.swift — DO NOT EDIT.
// Regenerate with: make version
//
// Version constants baked in at build time from git state. Accessible from both
// the app (WikiFS) and wikictl via the WikiFSCore dependency.

import Foundation

/// Build-time version constants resolved from git. Mirrors the Info.plist keys
/// written by build.sh (CFBundleShortVersionString, CFBundleVersion, WIKIGitSHA,
/// WIKIGitCommitCount, WIKIBuildVersion) so code and bundle stay in sync.
public enum GeneratedVersion {
    /// Marketing version (SemVer from tag or VERSION file, e.g. "0.5.0").
    /// Goes into CFBundleShortVersionString.
    public static let appVersion = "0.0.0"

    /// Short git SHA (e.g. "abc1234"). Goes into the WIKIGitSHA Info.plist key.
    public static let gitSHA = "911a76e"

    /// Git commit count — a monotone integer (e.g. "423"). Goes into
    /// WIKIGitCommitCount.
    public static let gitCommitCount = "518"

    /// Build identifier: "<count>-<sha>" (e.g. "423-abc1234"). Goes into
    /// CFBundleVersion.
    public static let buildVersion = "518-911a76e"

    /// Full display string: "<appVersion> (<buildVersion>)" — e.g. "0.5.0 (423-abc1234)".
    public static let fullVersionString = "0.0.0 (518-911a76e)"
}
