import Foundation

/// Shared File Provider container identifiers, as plain strings.
///
/// These are NOT `NSFileProviderItemIdentifier` values (that would drag a
/// `FileProvider` dependency into the core library) — they are just the raw
/// string keys. The File Provider extension (`Projection.Identity`) and the app
/// (`FileProviderSpike.signalChange()`) BOTH reference these so the two sides
/// can never silently drift apart: signaling the wrong container id would leave
/// the page list stale even after a correct enumerator fix.
public enum WikiFSContainerID {
    public static let pagesByID = "pages-by-id"
    public static let pagesByTitle = "pages-by-title"

    // Generated agent-facing index files (Phase 4, INITIAL §5). `manifest`
    // lives at the root; the two JSONL files live under the `indexes` folder.
    // The app's `signalChange()` signals `.rootContainer` + `indexes` so an edit
    // (which changes the generated bytes) invalidates these too.
    public static let manifest = "manifest"
    public static let indexes = "indexes"
    public static let indexPagesJSONL = "index-pages-jsonl"
    public static let indexLinksJSONL = "index-links-jsonl"

    // Ingested files (Phase 5). A brand-new top-level `files/` tree with `by-id`
    // and `by-name` views serving verbatim dropped-file bytes read-only. The
    // app's `signalChange()` signals these (plus the files.jsonl index) so an
    // ingest OR a removal refreshes the projection. `indexFilesJSONL` lives under
    // the existing `indexes` folder.
    public static let files = "files"
    public static let filesByID = "files-by-id"
    public static let filesByName = "files-by-name"
    public static let indexFilesJSONL = "index-files-jsonl"

    /// Prefix for a single ingested file's `by-id` LEAF identifier (carries the
    /// full ULID, never the filename — INITIAL §6). Shared so the extension's
    /// `Projection.Identity.fileByID(_:)` and the app's "open this file"
    /// resolution build the EXACT same identifier and can't drift.
    public static let fileByIDPrefix = "file-by-id:"

    /// Build the `by-id` leaf identifier string for an ingested file's ULID.
    public static func fileByID(_ ulid: String) -> String {
        fileByIDPrefix + ulid
    }
}
