import Foundation

/// Shared File Provider container identifiers, as plain strings.
///
/// These are NOT `NSFileProviderItemIdentifier` values (that would drag a
/// `FileProvider` dependency into the core library) — they are just the raw
/// string keys. The File Provider extension (`Projection.Identity`) and the app
/// (`FileProviderSpike.signalChange()`) BOTH reference these so the two sides
/// can never silently drift apart: signaling the wrong container id would leave
/// the page list stale even after a correct enumerator fix.
public enum WikiFSContainerID {
    public static let pagesByID = "pages-by-id"
    public static let pagesByTitle = "pages-by-title"

    // Generated agent-facing index files (Phase 4, INITIAL §5). `manifest`
    // lives at the root; the two JSONL files live under the `indexes` folder.
    // The app's `signalChange()` signals `.rootContainer` + `indexes` so an edit
    // (which changes the generated bytes) invalidates these too.
    public static let manifest = "manifest"
    public static let indexes = "indexes"
    public static let indexPagesJSONL = "index-pages-jsonl"
    public static let indexLinksJSONL = "index-links-jsonl"
}
