import Foundation

/// Shared File Provider container identifiers, as plain strings.
///
/// These are NOT `NSFileProviderItemIdentifier` values (that would drag a
/// `FileProvider` dependency into the core library) — they are just the raw
/// string keys. The File Provider extension (`Projection.Identity`) and the app
/// (`FileProviderSpike.signalChange()`) BOTH reference these so the two sides
/// can never silently drift apart: signaling the wrong container id would leave
/// the page list stale even after a correct enumerator fix.
public enum WikiFSContainerID {
    public static let pagesByID = "pages-by-id"
    public static let pagesByTitle = "pages-by-title"

    // Generated agent-facing index files (Phase 4, INITIAL §5). `manifest`
    // lives at the root; the two JSONL files live under the `indexes` folder.
    // The app's `signalChange()` signals `.rootContainer` + `indexes` so an edit
    // (which changes the generated bytes) invalidates these too.
    public static let manifest = "manifest"
    public static let indexes = "indexes"
    public static let indexPagesJSONL = "index-pages-jsonl"
    public static let indexLinksJSONL = "index-links-jsonl"

    // Sources (Phase 5, renamed v10). A brand-new top-level `sources/` tree with
    // `by-id` and `by-name` views serving verbatim source bytes read-only. The
    // app's `signalChange()` signals these (plus the sources.jsonl index) so an
    // ingest OR a removal refreshes the projection. `indexSourcesJSONL` lives
    // under the existing `indexes` folder.
    public static let sources = "sources"
    public static let sourcesByID = "sources-by-id"
    public static let sourcesByName = "sources-by-name"
    public static let indexSourcesJSONL = "index-sources-jsonl"

    // System prompt (v3). The user-editable singleton document projected
    // read-only at the wiki ROOT under TWO names with identical bytes:
    // `CLAUDE.md` and `AGENTS.md`. Both are children of the root, so the app's
    // `signalChange()` refreshes them by signaling `.rootContainer` (+ the
    // working set) — exactly as it already does for `manifest.json`.
    public static let claudeMD = "claude-md"
    public static let agentsMD = "agents-md"

    // Phase B. Two more root-level read-only docs:
    //  * `log.md`   — the append-only `log` table rendered as grep-able lines.
    //  * `index.md` — the singleton `wiki_index` catalog body, served verbatim.
    // Both are children of the root, so the app's `signalChange()` refreshes them
    // by signaling `.rootContainer` (+ the working set), exactly as for
    // `CLAUDE.md`/`AGENTS.md`/`manifest.json`.
    public static let logMD = "log-md"
    public static let indexMD = "index-md"

    // Phase C. A root-level read-only orientation map of the wiki's fixed layout
    // (`WikiTreeRenderer`) plus two live counts, served like `log.md`. A child of
    // the root, refreshed by `signalChange()` signaling `.rootContainer` (+ the
    // working set), exactly as for `log.md`/`index.md`.
    public static let treeMD = "tree-md"
    public static let wikiStructureMD = "wiki-structure-md"

    /// Prefix for a single source's `by-id` LEAF identifier (carries the
    /// full ULID, never the filename — INITIAL §6). Shared so the extension's
    /// `Projection.Identity.sourceByID(_:)` and the app's "open this source"
    /// resolution build the EXACT same identifier and can't drift.
    public static let sourceByIDPrefix = "source-by-id:"

    /// Build the `by-id` leaf identifier string for a source's ULID.
    public static func sourceByID(_ ulid: String) -> String {
        sourceByIDPrefix + ulid
    }

    /// Prefix for a single source's `by-name` LEAF identifier. Shared with the
    /// extension so `FileProviderSpike.resolveSourceByNameURL(id:)` and
    /// `Projection.Identity.sourceByName(_:)` use the same identifier.
    public static let sourceByNamePrefix = "source-by-name:"

    /// Build the `by-name` leaf identifier string for a source's ULID.
    public static func sourceByName(_ ulid: String) -> String {
        sourceByNamePrefix + ulid
    }

    // Bookmarks (#125, Phase D). A top-level `bookmarks/` tree mirrors the
    // user-defined folder/ref structure from `bookmark_nodes`. Folders are
    // directories; page/source refs are leaf files serving the target's content.
    public static let bookmarks = "bookmarks"
    public static let bookmarkFolderPrefix = "bookmark-folder:"
    public static let bookmarkPageRefPrefix = "bookmark-page-ref:"
    public static let bookmarkSourceRefPrefix = "bookmark-source-ref:"

    // Chats (#119 follow-on). A top-level `chats/` tree with `by-id` and
    // `by-name` views, each chat rendered as a readable `.md` transcript file.
    // The app's `signalChange()` signals `.rootContainer` (+ the working set)
    // so a chat create/rename/delete/append refreshes the projection.
    public static let chats = "chats"
    public static let chatsByID = "chats-by-id"
    public static let chatsByName = "chats-by-name"
    public static let indexChatsJSONL = "index-chats-jsonl"

    /// Prefix for a single chat's `by-id` LEAF identifier (carries the full
    /// ULID, never the title — INITIAL §6). Shared so the extension's
    /// `Projection.Identity.chatByID(_:)` and the app build the same identifier.
    public static let chatByIDPrefix = "chat-by-id:"

    /// Build the `by-id` leaf identifier string for a chat's ULID.
    public static func chatByID(_ ulid: String) -> String {
        chatByIDPrefix + ulid
    }

    /// Prefix for a single chat's `by-name` LEAF identifier.
    public static let chatByNamePrefix = "chat-by-name:"

    /// Build the `by-name` leaf identifier string for a chat's ULID.
    public static func chatByName(_ ulid: String) -> String {
        chatByNamePrefix + ulid
    }
}
