// tools/keychaingen/main.swift
//
// Generates Sources/WikiFSCore/GeneratedKeychain.swift at build time. Mirrors
// tools/versiongen/main.swift and tools/promptgen: the output is gitignored — a
// derived artifact (signing/local.config is already the per-developer source of
// truth, so a committed snapshot would diverge the moment someone else builds).
// `make keychain` (a prerequisite of build/check/test/release, alongside
// `version`/`prompts`) regenerates it; bare `swift build` does NOT — run
// `make keychain` first (CI runs `make version prompts keychain`).
//
// What it bakes in:
//   accessGroup — "<TEAM_ID>.<suffix>" shared by the app + the wikid daemon so
//     the daemon can read the ACP API keys the app wrote to the Keychain. Read
//     from signing/local.config: an explicit KEYCHAIN_ACCESS_GROUP override
//     wins; otherwise derived from TEAM_ID + APP_GROUP (the App Group with its
//     leading "group." stripped — so APP_GROUP="group.com.example.wiki" yields
//     "com.example.wiki"). App + daemon link this module, so the SAME constant
//     reaches both — no Bundle.main / Info.plist lookup at runtime.
//
// Empty string when signing/local.config is absent (fresh clones / CI / tests) —
// "no group" semantics: KeychainSecretStore then uses the legacy file-based
// keychain with no access group, preserving the pre-sharing behavior so the test
// runner (no entitlements) round-trips Keychain ops without errSecMissingEntitlement.
//
// build.sh and the Makefile derive the SAME value (same formula, same override)
// for the generated entitlements, so app, daemon, and code agree for ANY
// developer who clones + runs signing/setup.sh. See plans/keychain-sharing.md.
//
// Run:
//   swift tools/keychaingen/main.swift          overwrite the generated file
//   swift tools/keychaingen/main.swift --stdout  write to stdout
//
// The script only writes the file if content actually changed, so making it a
// .PHONY prerequisite of build/check/test doesn't force recompilation on every
// invocation — only when the developer's configured group actually changes.

import Foundation

// MARK: - Shell + config helpers

/// Run a shell command and return its trimmed stdout. Returns nil on failure.
func shell(_ command: String) -> String? {
    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/env")
    process.arguments = ["sh", "-c", command]
    let pipe = Pipe()
    process.standardOutput = pipe
    process.standardError = Pipe() // swallow errors
    do {
        try process.run()
        process.waitUntilExit()
        guard process.terminationStatus == 0 else { return nil }
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
    } catch {
        return nil
    }
}

/// Parse shell-style `KEY=VALUE` lines (comments `#…` skipped, surrounding
/// whitespace trimmed, surrounding double quotes stripped). Same rules as
/// WikiIdentifiers.parseKV. Returns nil when the file is absent/unreadable.
func parseLocalConfig(_ path: String) -> [String: String]? {
    guard let text = try? String(contentsOfFile: path, encoding: .utf8) else { return nil }
    var out: [String: String] = [:]
    for raw in text.split(whereSeparator: \.isNewline) {
        let line = raw.trimmingCharacters(in: .whitespaces)
        guard !line.isEmpty, !line.hasPrefix("#"), let eq = line.firstIndex(of: "=") else { continue }
        let key = String(line[..<eq]).trimmingCharacters(in: .whitespaces)
        var value = String(line[line.index(after: eq)...]).trimmingCharacters(in: .whitespaces)
        if value.count >= 2, value.hasPrefix("\""), value.hasSuffix("\"") {
            value = String(value.dropFirst().dropLast())
        }
        out[key] = value
    }
    return out
}

// MARK: - Resolve the access group

/// "<TEAM_ID>.<suffix>" where suffix is APP_GROUP minus a leading "group.".
/// Empty when local.config is absent or either value is missing — "no group"
/// semantics (legacy file keychain). Honors an explicit KEYCHAIN_ACCESS_GROUP
/// override in local.config first (one override point for app entitlements +
/// this constant); otherwise derives it, matching build.sh's:
///   KEYCHAIN_ACCESS_GROUP="${KEYCHAIN_ACCESS_GROUP:-${TEAM_ID}.${APP_GROUP#group.}}"
func resolveAccessGroup() -> String {
    guard let cfg = parseLocalConfig("signing/local.config") else { return "" }
    if let explicit = cfg["KEYCHAIN_ACCESS_GROUP"], !explicit.isEmpty { return explicit }
    let teamID = cfg["TEAM_ID"] ?? ""
    var appGroup = cfg["APP_GROUP"] ?? ""
    if appGroup.hasPrefix("group.") { appGroup.removeFirst("group.".count) }
    guard !teamID.isEmpty, !appGroup.isEmpty else { return "" }
    return "\(teamID).\(appGroup)"
}
let accessGroup = resolveAccessGroup()

// MARK: - Generate Swift source

let output = """
// Sources/WikiFSCore/GeneratedKeychain.swift
//
// GENERATED by tools/keychaingen/main.swift — DO NOT EDIT.
// Regenerate with: make keychain
//
// The shared Keychain access group, baked in at build time from
// signing/local.config (TEAM_ID + APP_GROUP). App + wikid daemon link this
// module, so the SAME constant reaches both — no Bundle.main / Info.plist
// lookup at runtime. Empty when signing/local.config is absent (fresh clones,
// CI, `swift test`) — "no group" → KeychainSecretStore uses the legacy
// file-based keychain with no access group.

import Foundation

/// Build-time Keychain access group (app + wikid daemon share it so the daemon
/// can read the ACP/Extraction/Zotero secrets the app wrote). Regenerated from
/// signing/local.config by `make keychain`; see tools/keychaingen. Empty when
/// unconfigured → no `kSecAttrAccessGroup` / no DataProtection keychain.
public enum GeneratedKeychain {
    public static let accessGroup = \"\(accessGroup)\"
}

"""

// MARK: - Write

let outputPath = "Sources/WikiFSCore/GeneratedKeychain.swift"

let useStdout = CommandLine.arguments.contains("--stdout")
if useStdout {
    FileHandle.standardOutput.write(Data(output.utf8))
    exit(0)
}

let existingContent = (try? String(contentsOfFile: outputPath, encoding: .utf8)) ?? ""
if output == existingContent {
    // No change — skip writing to avoid touching the file's mtime (which would
    // trigger an unnecessary swift recompile).
    exit(0)
}

try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("✓ regenerated \(outputPath)")
