// Generated by scripts/sync-acp-adapter.sh — the compiled-in pin for the
// vendored Claude ACP adapter (issue #1257 Level 2). NEVER hand-edit: change
// ADAPTER_VERSION in the sync script and run `make acp-adapter-sync`, then
// review the generated diff. The version-bearing records
// (tools/claude-acp-adapter/adapter.lock.json,
// tools/claude-acp-adapter/package.json, and this file) are rewritten
// together from that one variable; a hand edit makes
// `scripts/sync-acp-adapter.sh --check` fail by design.

/// Compile-time pin for the vendored Claude ACP adapter bundle.
///
/// `ACPBackend` rewrites an adapter-shaped launch
/// (`bun x <spec>` / `bun x <spec>@<version>`) to run the committed
/// single-file bundle through the resolved bun when the spec matches
/// `vendoredAdapterPackageSpec` — bare, or pinned at exactly
/// `vendoredAdapterPinnedVersion`. Any other version keeps the configured
/// package-runner launch (the user asked for that version; the vendored
/// bundle is not it). `vendoredAdapterBundleName` names the file `build.sh`
/// stages into `Contents/Helpers`.
public enum VendoredAdapterPin {
    /// The npm package spec the committed bundle was built from.
    public static let vendoredAdapterPackageSpec = "@agentclientprotocol/claude-agent-acp"

    /// The exact upstream version vendored into the committed bundle.
    public static let vendoredAdapterPinnedVersion = "0.77.0"

    /// The helper name `build.sh` stages into `Contents/Helpers`.
    public static let vendoredAdapterBundleName = "claude-acp-adapter.js"
}
